//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSPService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSPService.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_activedays`;.
        /// </summary>
        internal static string DeleteActiveDays {
            get {
                return ResourceManager.GetString("DeleteActiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_activeperiods`;.
        /// </summary>
        internal static string DeleteActivePeriods {
            get {
                return ResourceManager.GetString("DeleteActivePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_airports`;.
        /// </summary>
        internal static string DeleteAirports {
            get {
                return ResourceManager.GetString("DeleteAirports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_airspaces`;.
        /// </summary>
        internal static string DeleteAirspaces {
            get {
                return ResourceManager.GetString("DeleteAirspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_atcstations`;.
        /// </summary>
        internal static string DeleteAtcStations {
            get {
                return ResourceManager.GetString("DeleteAtcStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_cities`;.
        /// </summary>
        internal static string DeleteCities {
            get {
                return ResourceManager.GetString("DeleteCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_countries`;.
        /// </summary>
        internal static string DeleteCountries {
            get {
                return ResourceManager.GetString("DeleteCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_firs`;.
        /// </summary>
        internal static string DeleteFirs {
            get {
                return ResourceManager.GetString("DeleteFirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_fixes`;.
        /// </summary>
        internal static string DeleteFixes {
            get {
                return ResourceManager.GetString("DeleteFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_frequencies`;.
        /// </summary>
        internal static string DeleteFrequencies {
            get {
                return ResourceManager.GetString("DeleteFrequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_navaids`;.
        /// </summary>
        internal static string DeleteNavaids {
            get {
                return ResourceManager.GetString("DeleteNavaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_regions`;.
        /// </summary>
        internal static string DeleteRegions {
            get {
                return ResourceManager.GetString("DeleteRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM `airnavdb`.`tbl_runways`;.
        /// </summary>
        internal static string DeleteRunways {
            get {
                return ResourceManager.GetString("DeleteRunways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_airports`
        ///(`id`,
        ///`ident`,
        ///`type`,
        ///`name`,
        ///`latitude_deg`,
        ///`longitude_deg`,
        ///`elevation_ft`,
        ///`continent`,
        ///`iso_country`,
        ///`iso_region`,
        ///`municipality`,
        ///`scheduled_service`,
        ///`gps_code`,
        ///`iata_code`,
        ///`local_code`,
        ///`home_link`,
        ///`wikipedia_link`,
        ///`keywords`)
        ///VALUES
        ///(@id,
        ///@ident,
        ///@type,
        ///@name,
        ///@latitude_deg,
        ///@longitude_deg,
        ///@elevation_ft,
        ///@continent,
        ///@iso_country,
        ///@iso_region,
        ///@municipality,
        ///@scheduled_service,
        ///@gps_code,
        ///@iata_code,
        ///@local_code,
        ///@home_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertAirports {
            get {
                return ResourceManager.GetString("InsertAirports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_cities`
        ///(`geonameid`,
        ///`name`,
        ///`asciiname`,
        ///`alternatenames`,
        ///`latitude`,
        ///`longitude`,
        ///`feature_class`,
        ///`feature_code`,
        ///`country_code`,
        ///`continent`,
        ///`cc2`,
        ///`admin1_code`,
        ///`admin2_code`,
        ///`admin3_code`,
        ///`admin4_code`,
        ///`population`,
        ///`elevation`,
        ///`dem`,
        ///`timezone`,
        ///`modification_date`)
        ///VALUES
        ///(@geonameid,
        ///@name,
        ///@asciiname,
        ///@alternatenames,
        ///@latitude,
        ///@longitude,
        ///@feature_class,
        ///@feature_code,
        ///@country_code,
        ///@continent,
        ///@cc2,
        ///@admin1_code,
        ///@admin2_cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertCities {
            get {
                return ResourceManager.GetString("InsertCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_countries`
        ///(`_id`,
        ///`id`,
        ///`code`,
        ///`name`,
        ///`continent`,
        ///`wikipedia_link`,
        ///`keywords`)
        ///VALUES
        ///(@_id,
        ///@id,
        ///@code,
        ///@name,
        ///@continent,
        ///@wikipedia_link,
        ///@keywords);.
        /// </summary>
        internal static string InsertCountries {
            get {
                return ResourceManager.GetString("InsertCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_firs`
        ///(`_id`,
        ///`id`,
        ///`ident`,
        ///`name`,
        ///`position`,
        ///`polygon`)
        ///VALUES
        ///(@_id,
        ///@id,
        ///@ident,
        ///@name,
        ///@position,
        ///@polygon);.
        /// </summary>
        internal static string InsertFirs {
            get {
                return ResourceManager.GetString("InsertFirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_fixes`
        ///(`_id`,
        ///`ident`,
        ///`latitude_deg`,
        ///`longitude_deg`,
        ///`continent`)
        ///VALUES
        ///(@_id,
        ///@ident,
        ///@latitude_deg,
        ///@longitude_deg,
        ///@continent);.
        /// </summary>
        internal static string InsertFixes {
            get {
                return ResourceManager.GetString("InsertFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_frequencies`
        ///(`id`,
        ///`airport_ref`,
        ///`airport_ident`,
        ///`type`,
        ///`description`,
        ///`frequency_mhz`)
        ///VALUES
        ///(@id,
        ///@airport_ref,
        ///@airport_ident,
        ///@type,
        ///@description,
        ///@frequency_mhz);.
        /// </summary>
        internal static string InsertFrequencies {
            get {
                return ResourceManager.GetString("InsertFrequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_navaids`
        ///(`_id`,
        ///`id`,
        ///`filename`,
        ///`ident`,
        ///`name`,
        ///`type`,
        ///`frequency_khz`,
        ///`latitude_deg`,
        ///`longitude_deg`,
        ///`elevation_ft`,
        ///`iso_country`,
        ///`continent`,
        ///`dme_frequency_khz`,
        ///`dme_channel`,
        ///`dme_latitude_deg`,
        ///`dme_longitude_deg`,
        ///`dme_elevation_ft`,
        ///`slaved_variation_deg`,
        ///`magnetic_variation_deg`,
        ///`usageType`,
        ///`power`,
        ///`associated_airport`,
        ///`associated_airport_id`)
        ///VALUES
        ///(@_id,
        ///@id,
        ///@filename,
        ///@ident,
        ///@name,
        ///@type,
        ///@frequency_khz,
        ///@latitude_deg, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertNavaids {
            get {
                return ResourceManager.GetString("InsertNavaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_regions`
        ///(`_id`,
        ///`id`,
        ///`code`,
        ///`local_code`,
        ///`name`,
        ///`continent`,
        ///`iso_country`,
        ///`wikipedia_link`,
        ///`keywords`)
        ///VALUES
        ///(@_id,
        ///@id,
        ///@code,
        ///@local_code,
        ///@name,
        ///@continent,
        ///@iso_country,
        ///@wikipedia_link,
        ///@keywords);.
        /// </summary>
        internal static string InsertRegions {
            get {
                return ResourceManager.GetString("InsertRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_runways`
        ///(`id`,
        ///`airport_ref`,
        ///`airport_ident`,
        ///`length_ft`,
        ///`width_ft`,
        ///`lighted`,
        ///`closed`,
        ///`surface`,
        ///`le_ident`,
        ///`le_latitude_deg`,
        ///`le_longitude_deg`,
        ///`le_elevation_ft`,
        ///`le_heading_degT`,
        ///`le_displaced_threshold_ft`,
        ///`he_ident`,
        ///`he_latitude_deg`,
        ///`he_longitude_deg`,
        ///`he_elevation_ft`,
        ///`he_heading_degT`,
        ///`he_displaced_threshold_ft`)
        ///VALUES
        ///(@id,
        ///@airport_ref,
        ///@airport_ident,
        ///@length_ft,
        ///@width_ft,
        ///@lighted,
        ///@closed,
        ///@surface,
        ///@le_ident,
        ///@le_la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertRumways {
            get {
                return ResourceManager.GetString("InsertRumways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `airnavdb`.`tbl_tiles`
        ///(`_id`,
        ///`name`,
        ///`region`,
        ///`type`,
        ///`mbtileslink`,
        ///`xmllink`,
        ///`version`,
        ///`startValidity`,
        ///`endValidity`)
        ///VALUES
        ///(@_id,
        ///@name,
        ///@region,
        ///@type,
        ///@mbtileslink,
        ///@xmllink,
        ///@version,
        ///@startValidity,
        ///@endValidity);.
        /// </summary>
        internal static string InsertTiles {
            get {
                return ResourceManager.GetString("InsertTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM `airnavdb`.`tbl_links` WHERE enabled=1;.
        /// </summary>
        internal static string SelectLinks {
            get {
                return ResourceManager.GetString("SelectLinks", resourceCulture);
            }
        }
    }
}
